language: haskell

jobs:
  include:
    - stage: test
      install:
        - cabal update
        - cabal install --enable-tests --verbose=2

    - stage: deploy
      before_install:
        - cabal --version
      install: skip
      script: skip
      deploy:
        provider: hackage
        username: VictorDenisov
        password:
          secure: iM14fPVAVWRS1UZ3gxW2RXup4E1OIppTpCOgIdhWghhhHIKEMNaB8mnFT0+KHYp3iKjW0PUXu9xaEEzPJRsWjrcBYtG7Xim2kIrQzve6pDKQ3FBXYbknvxYqmzW43cO5bkDhlaaHP/8nswURjobw9a786loxelpQahtdeT1x2yc=
        on:
          repo: mongodb-haskell/bson
          tags: true
